create TABLE CLIENTE
(
CD_CLIENTE INT PRIMARY KEY auto_increment,
NM_CLIENTE VARCHAR(50) NOT null,
CPF CHAR(11) NOT NULL UNIQUE,
CELULAR CHAR(11) NOT NULL,
EMAIL VARCHAR(50) NOT null,
CIDADE VARCHAR(50) NOT NULL,
ESTADO char(2) NOT NULL,
CEP char(8),
TIPO_LOGRADOURO VARCHAR(15) NOT NULL,
NM_LOGRADOURO VARCHAR(60) NOT NULL,
NR_LOGRADOURO VARCHAR(6) NOT NULL,
COMPLEMENTO VARCHAR(30)
)

/*DROP TABLE cliente*/

CREATE TABLE CONTATO_TELEFONICO(
CD_CONTATO_TELEFONICO INT PRIMARY KEY AUTO_INCREMENT,
CD_CLIENTE INT  NOT NULL ,
DDI VARCHAR(5) NOT NULL,
DDD VARCHAR(5) NOT NULL,
NUMERO_CONTATO CHAR(9) NOT NULL
)

ALTER TABLE CONTATO_TELEFONICO
ADD CONSTRAINT FK_CONTATO_TELEFONICO_CLIENTE
FOREIGN KEY (CD_CLIENTE) REFERENCES cliente (CD_CLIENTE)


CREATE TABLE ANIMAL
(
CD_ANIMAL INT PRIMARY KEy AUTO_INCREMENT,
CD_CLIENTE INT NOT NULL,
NM_ANIMAL VARCHAR(50) NOT null,
ESPECIE VARCHAR(50) NOT null,
RACA VARCHAR(50) NOT NULL,
PESO DECIMAL(5,2) NOT NULL,
PORTE CHAR(1) NOT NULL,
SEXO CHAR(1) NOT NULL,
DT_NASCIMENTO DATETIME NOT NULL,
CONSTRAINT CHK_SEXO_ANIMAL CHECK (SEXO IN ('M', 'S')),
CONSTRAINT CHK_PORTE_ANIMAL CHECK (PORTE IN ('P', 'M', 'G')),
CONSTRAINT FK_ANIMAL_CLIENTE FOREIGN KEY (CD_CLIENTE)
REFERENCES cliente (CD_CLIENTE)
)

CREATE TABLE TIPO_SERVICO
(
	CD_TIPO_SERVICO INT PRIMARY KEY AUTO_INCREMENT,
	NM_SERVICO VARCHAR(50) NOT NULL,
	VL_SERVICO DECIMAL(10,2) NOT NULL
)


CREATE TABLE VETERINARIO 
(
	CD_VETERINARIO INT PRIMARY KEY AUTO_INCREMENT,
	NM_VETERINARIO VARCHAR(50) NOT NULL,
	CRMV VARCHAR(20) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	ESPECIALIDADE VARCHAR(50)	
)

CREATE TABLE CONSULTA 
(
	CD_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	CD_ANIMAL INT NOT NULL,
	CD_VETERINARIO INT NOT NULL,
	DT_CONSULTA DATETIME NOT NULL,
	IC_PAGO BIT NOT NULL,
	FORMA_PAGAMENTO VARCHAR(50) NOT NULL,
	QNT_VEZES TINYINT,
	VL_TOTAL DECIMAL(10,2) NOT null,
	VL_PAGO DECIMAL(10,2),	
	CONSTRAINT FK_CONSULTA_ANIMAL FOREIGN KEY (CD_ANIMAL)
	REFERENCES animal (CD_ANIMAL),
	CONSTRAINT FK_CONSULTA_VETERINARIO FOREIGN KEY (CD_VETERINARIO)
	REFERENCES veterinario (CD_VETERINARIO)
)

CREATE TABLE CONSULTA_TIPO_SERVICO
(
	CD_CONSULTA_TIPO_SERVICO INT PRIMARY KEY AUTO_INCREMENT,
	CD_CONSULTA INT NOT NULL,
	CD_TIPO_SERVICO INT NOT NULL,
	VL_SERVICO DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_CONSULTA_TIPO_SERVICO_CONSULTA FOREIGN KEY (CD_CONSULTA)
	REFERENCES consulta (CD_CONSULTA),
	CONSTRAINT FK_TIPO_SERVICO FOREIGN KEY (CD_TIPO_SERVICO)
	REFERENCES tipo_servico	(CD_TIPO_SERVICO)	
)
