/*CREATE DATABASE JucaRentBeach*/
USE jucarentbeach

CREATE TABLE CLIENTE
(
	CD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NM_CLIENTE VARCHAR(50) NOT NULL,
	CPF CHAR (11) NOT NULL UNIQUE	
)

CREATE TABLE FUNCIONARIO
(
	CD_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
	NM_FUNCIONARIO VARCHAR(50) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	CELULAR CHAR(11) NOT NULL
)

CREATE TABLE EQUIPAMENTO
(
	CD_EQUIPAMENTO INT PRIMARY KEY  AUTO_INCREMENT,
	NM_EQUIPAMENTO VARCHAR(50) UNIQUE NOT NULL,
	QTD INT NOT NULL,
	VL_HORA DECIMAL (5,2) NOT NULL
)

CREATE TABLE ALUGUEL
(
	CD_ALUGUEL INT PRIMARY KEY AUTO_INCREMENT,
	CD_CLIENTE INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_RETIRADA DATETIME NOT NULL,
	DT_DEVOLUCAO DATETIME,
	VL_A_PAGAR DECIMAL(10,2),
	VL_PAGO DECIMAL (10,2),
	PAGO BIT,
	FORMA_PAGAMENTO VARCHAR(50),
	QNT_VEZES INT,
	CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (CD_CLIENTE)
	REFERENCES CLIENTE (CD_CLIENTE),
	CONSTRAINT FK_ALUGUEL_FUNCIONARIO FOREIGN KEY (CD_FUNCIONARIO)
	REFERENCES FUNCIONARIO (CD_FUNCIONARIO),
	CONSTRAINT CHK_FORMA_PAGAMENTO CHECK 
	(FORMA_PAGAMENTO IN ('DINHEIRO','PIX','DÉBITO','CRÉDITO'))
)

CREATE TABLE ALUGUEL_EQUIPAMENTO
(
	CD_ALUGUEL_EQUIPAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	CD_EQUIPAMENTO INT NOT NULL,
	CD_ALUGUEL INT NOT NULL,
	VL_ITEM DECIMAL (10,2) NOT NULL,
	VL_UNITARIO DECIMAl(10,2)NOT NULL,
	QTD INT,
	CONSTRAINT FK_ALUGUEL_EQUIPAMENTO_EQUIPAMENTO FOREIGN KEY (CD_EQUIPAMENTO)
	REFERENCES EQUIPAMENTO (CD_EQUIPAMENTO),
	CONSTRAINT FK_ALUGUEL_EQUIPAMENTO_ALUGUEL FOREIGN KEY (CD_ALUGUEL)
	REFERENCES ALUGUEL(CD_ALUGUEL)
)